"""initial schema: users, club_specs, swing_sessions, shots

Revision ID: 07d425b4a759
Revises: 
Create Date: 2026-03-29 15:04:37.832141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d425b4a759'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('club_type', sa.String(), nullable=False),
    sa.Column('loft', sa.Float(), nullable=True),
    sa.Column('lie_angle', sa.Float(), nullable=True),
    sa.Column('shaft_options', sa.Text(), nullable=True),
    sa.Column('head_weight', sa.Float(), nullable=True),
    sa.Column('adjustable', sa.Boolean(), nullable=False),
    sa.Column('loft_range_min', sa.Float(), nullable=True),
    sa.Column('loft_range_max', sa.Float(), nullable=True),
    sa.Column('launch_bias', sa.String(), nullable=True),
    sa.Column('spin_bias', sa.String(), nullable=True),
    sa.Column('forgiveness_rating', sa.Integer(), nullable=True),
    sa.Column('workability_rating', sa.Integer(), nullable=True),
    sa.Column('swing_speed_min', sa.Float(), nullable=True),
    sa.Column('swing_speed_max', sa.Float(), nullable=True),
    sa.Column('msrp', sa.Float(), nullable=True),
    sa.Column('avg_used_price', sa.Float(), nullable=True),
    sa.Column('affiliate_url_template', sa.String(), nullable=True),
    sa.Column('still_in_production', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('swing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=True),
    sa.Column('launch_monitor_type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('trackman_session_id', sa.String(), nullable=True),
    sa.Column('trackman_facility_name', sa.String(), nullable=True),
    sa.Column('trackman_bay_id', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('source_file_name', sa.String(), nullable=True),
    sa.Column('source_file_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('club_used', sa.String(), nullable=False),
    sa.Column('club_brand', sa.String(), nullable=True),
    sa.Column('club_model', sa.String(), nullable=True),
    sa.Column('ball_speed', sa.Float(), nullable=False),
    sa.Column('launch_angle', sa.Float(), nullable=False),
    sa.Column('spin_rate', sa.Float(), nullable=False),
    sa.Column('spin_axis', sa.Float(), nullable=True),
    sa.Column('carry_distance', sa.Float(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('club_speed', sa.Float(), nullable=True),
    sa.Column('smash_factor', sa.Float(), nullable=True),
    sa.Column('attack_angle', sa.Float(), nullable=True),
    sa.Column('club_path', sa.Float(), nullable=True),
    sa.Column('face_angle', sa.Float(), nullable=True),
    sa.Column('face_to_path', sa.Float(), nullable=True),
    sa.Column('offline_distance', sa.Float(), nullable=True),
    sa.Column('apex_height', sa.Float(), nullable=True),
    sa.Column('landing_angle', sa.Float(), nullable=True),
    sa.Column('dynamic_loft', sa.Float(), nullable=True),
    sa.Column('spin_loft', sa.Float(), nullable=True),
    sa.Column('hang_time', sa.Float(), nullable=True),
    sa.Column('last_data_distance', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['swing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shots')
    op.drop_table('swing_sessions')
    op.drop_table('users')
    op.drop_table('club_specs')
    # ### end Alembic commands ###
