"""add recommended_build to recommendations

Revision ID: 4f68b27d2180
Revises: 17ba1067f835
Create Date: 2026-03-30 14:22:44.097294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f68b27d2180'
down_revision: Union[str, Sequence[str], None] = '17ba1067f835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('recommended_build', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'recommended_build')
    # ### end Alembic commands ###
