"""add affiliate_clicks and price_cache tables

Revision ID: 722feb52000d
Revises: 07d425b4a759
Create Date: 2026-03-29 16:51:13.466559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722feb52000d'
down_revision: Union[str, Sequence[str], None] = '07d425b4a759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_spec_id', sa.Integer(), nullable=False),
    sa.Column('retailer', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_spec_id', 'retailer', name='uq_club_retailer')
    )
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_spec_id', sa.Integer(), nullable=False),
    sa.Column('retailer', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliate_clicks')
    op.drop_table('price_cache')
    # ### end Alembic commands ###
