"""add scrape_logs table, review_summary, price_cache fields

Revision ID: 7c644ccaa44d
Revises: 7a4b42a546b5
Create Date: 2026-03-30 13:41:34.555028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c644ccaa44d'
down_revision: Union[str, Sequence[str], None] = '7a4b42a546b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraper_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('clubs_found', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('ran_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('club_specs') as batch_op:
        batch_op.add_column(sa.Column('review_summary', sa.Text(), nullable=True))
    with op.batch_alter_table('price_cache') as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('product_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cache') as batch_op:
        batch_op.drop_column('product_url')
        batch_op.drop_column('is_available')
    with op.batch_alter_table('club_specs') as batch_op:
        batch_op.drop_column('review_summary')
    op.drop_table('scrape_logs')
    # ### end Alembic commands ###
